export const enum STATUS_DEMAND {
  ANDAMENTO = "EM ANDAMENTO",
  PLANEJAMENTO = "PLANEJAMENTO",
  CONCLUIDO = "CONCLUIDO",
}
export const STATUS_DEMAND_AS_CONST = [
  "EM ANDAMENTO",
  "PLANEJAMENTO",
  "CONCLUIDO",
] as const;
